### ISSUE TITLE
Duplicate modes issue

### ISSUE THREAD

**Issue by phurth** [disforw/goveelife#3]
I'm testing this integration with my H7131 space heater and it seems to control the device, however there is an oddity in that the modes listed on the climate entity in HA are duplicated. Fan, Auto, gearMode:Low, gearMode:Medium, and gearMode:High are all listed twice. I also have an H7135 heater that shows the same duplication.

Any idea why this would be?

**Comment by disforw** [comment]
This should be fixed in a beta, can you try updating to 2.5 and let me know if fixed?

**Comment by phurth** [comment]
I updated to 2.5 but both climate entities (H7131, H7135) still showed duplicate entries. I then tried deleting and re-adding, but the modes then appeared 4 times each. I removed the devices, restarted HA, and re-added and now I'm back to the original duplication of modes. So, the bottom line is that the 2.5 beta didn't fix the duplication.

I did also try 2.t which appears to be a bit newer but that made no difference. Please let me know if there's anything else I can do to help troubleshoot. I like your approach with the climate entity much better than the other option (Govee2MQTT).

**Comment by phurth** [comment]
I tried the 2.1 release from 5/5. The duplication issue is still present. I also have two H7123 air purifiers which no longer show modes (they used to). Now they are just on/off.

**Comment by disforw** [comment]
So i was able to recreate this, but only when first setting up. This clears for me after a reboot. I’m not going to call it fixed, but a simple reboot should do the fix while I investigate how to run through the presets a single time.

**Comment by phurth** [comment]
I've updated to 2.9 and restarted HA. On the air purifiers (H7123) the presets are back but are duplicated (though there is no "sleep" preset). For the space heaters (H7131, H7135), duplication is still present. I'm attaching screenshots so you can see what I'm seeing.
![device_screenshots_1](https://github.com/disforw/goveelife/assets/11875352/295c01a0-1dda-406e-962a-b294c98ab505)
![device_screenshots_2](https://github.com/disforw/goveelife/assets/11875352/b50debd1-6126-4096-afc7-dc8922da7291)
![device_screenshots_3](https://github.com/disforw/goveelife/assets/11875352/bf579bb5-1ef0-4f14-b004-7ca5705762b0)

**Comment by KyleStilkey** [comment]
I'm adding myself to the list, all my fans and purifiers are showing duplicate modes.

**Comment by disforw** [comment]
Resolved in release 3.1.0

**Comment by KyleStilkey** [comment]
This is not fixed, my devices still have duplicated modes.

![image](https://github.com/user-attachments/assets/bcb77e40-16fa-40b4-85f9-66be74ea45c7)

**Comment by disforw** [comment]
Can you please try removing, rebooting, and readding?

**Comment by KyleStilkey** [comment]
> Can you please try removing, rebooting, and readding?

Yes I already did that before posting.

I have opened an issue about this before but will post it here, I'm unsure if these are due to them but I get these filling up my logs.

This error originated from a custom integration.

Logger: custom_components.goveelife.entities
Source: custom_components/goveelife/entities.py:76
integration: Govee Life (documentation)
First occurred: 1:42:06 AM (9 occurrences)
Last logged: 1:42:06 AM

GoveeLife - 0b7bd4adfcbb5420_fan: __init__ failed: 'value' (builtins.KeyError)
GoveeLife - 10476074f413d7cc_fan: __init__ failed: 'value' (builtins.KeyError)
GoveeLife - 11c5d4adfce89568_fan: __init__ failed: 'value' (builtins.KeyError)
GoveeLife - 2a93d0c907006382_fan: __init__ failed: 'value' (builtins.KeyError)
GoveeLife - 29e26074f4cc4152_fan: __init__ failed: 'value' (builtins.KeyError)
This error originated from a custom integration.

Logger: custom_components.goveelife.fan
Source: custom_components/goveelife/fan.py:157
integration: Govee Life (documentation)
First occurred: 1:42:06 AM (18 occurrences)
Last logged: 1:44:05 AM

GoveeLife - 11c5d4adfce89568_fan: preset_mode: invalid value: {'workMode': 3, 'modeValue': 0}
GoveeLife - 2a93d0c907006382_fan: preset_mode: invalid value: {'workMode': 1, 'modeValue': 6}
GoveeLife - 137ed4adfc5061a2_fan: preset_mode: invalid value: {'workMode': 3, 'modeValue': 0}
GoveeLife - 1c25d4adfc44801a_fan: preset_mode: invalid value: {'workMode': 1, 'modeValue': 6}
GoveeLife - 0b7bd4adfcbb5420_fan: preset_mode: invalid value: {'workMode': 1, 'modeValue': 8}

**Comment by phurth** [comment]
I'm still seeing this, even with a newly added device (H7123 air purifier).

**Comment by disforw** [comment]
One of the earlier versions of this integration allowed for multiple modes to be added into the attribute in the entity database. The entities need to be eradicated from the database in order to write the new ones. Therefore the integration now asks you to do a reboot after removal. Have you rebooted HA after full removal of the integration?

**Comment by KyleStilkey** [comment]
> One of the earlier versions of this integration allowed for multiple modes to be added into the attribute in the entity database. The entities need to be eradicated from the database in order to write the new ones. Therefore the integration now asks you to do a reboot after removal. Have you rebooted HA after full removal of the integration?

Yes.

**Comment by TheodorusL** [comment]
I have 6 heaters. Each heater has the modes 6 times. It seems to me that with each time a heater is added, the modes of that heater are added to ALL heaters, instead of only to the new heater.

I'm running the latest version: 3.1.0.
